pubdisk/blueprints/auth.py
# -*- coding: utf-8 -*-
"""
:author: Zhazh
:copyright: © 2020 Zhazh <zhazh1985@163.com>
:license: MIT, see LICENSE for more details.
"""

from flask import current_app, render_template, redirect, url_for, Blueprint, request, jsonify
from flask_login import login_user, logout_user, login_required, current_user

from pubdisk.extensions import db
from pubdisk.blueprints import login_redirect, user_required
from pubdisk.forms import LoginForm, ChangePasswordForm
from pubdisk.models import User

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
@login_redirect
def login():
    form = LoginForm()
    if form.validate_on_submit():
        if User.check(form.username.data, form.password.data):
            user = User.query.filter(User.name == form.username.data).first()
            login_user(user, remember=form.remember_me.data)
            if user.role_admin:
                return redirect(url_for('admin.index'))
            else:
                next = request.args.get('next')
                return redirect(next or url_for('users.main'))
        else:
            form.username.errors.append("Incorrect username or password")
    return render_template('auth/login.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

# used by ajax method
@auth_bp.route('/change-password', methods=['POST'])
@user_required('json')
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        try:
            if current_user.equal_password(form.old_password.data):
                current_user.set_password(form.new_password.data)
                db.session.commit()
                logout_user()
            else:
                return jsonify(dict(code=1, msg='Incorrect old password.'))
        except Exception as e:
            db.session.rollback()
            current_app.logger.warning("User[%r] change_password occurred an error:%s"%(current_user, str(e)))
            return jsonify(dict(code=2, msg='Database exception.'))
    else:
        msg = ''
        for field, errors in form.errors.items():
            msg = "'%s':"%field
            for error in errors:
                msg = msg + ' ' + error
        if msg != '':
            return jsonify(dict(code=3, msg=msg))
    return jsonify(dict(code=0, msg='Success'))

pubdisk/blueprints/users.py
# -*- coding: utf-8 -*-
"""
:author: Zhazh
:copyright: © 2020 Zhazh <zhazh1985@163.com>
:license: MIT, see LICENSE for more details.
"""

import os
from flask import (
        render_template, redirect, url_for, request, jsonify, abort,
        Blueprint, current_app, send_from_directory, make_response
)
from flask_login import login_user, logout_user, login_required, current_user

from pubdisk.extensions import db
from pubdisk.blueprints import login_redirect, user_required
from pubdisk.utils import Node, NodeTypes

users_bp = Blueprint('users', __name__)

@users_bp.route('/')
@login_redirect
def index():
    return redirect(url_for('auth.login'))

#: main page will load other page by ajax get method.
@users_bp.route('/main')
@login_required
def main():
    return render_template('users/main.html')

# get by ajax method
@users_bp.route('/home', methods=["GET"])
@user_required('html')
def home():
    path = request.args.get('path', '/')
    node = Node(path)
    return render_template('users/_home.html', paths=node.layer_path, node_list=node.children)

@users_bp.route('/download', methods=["GET"])
@user_required('html')
def download():
    path = request.args.get('path', '/')
    node = Node(path)
    if not os.path.exists(node.local_path) or not os.path.isfile(node.local_path):
        abort(400)
    _path, _filename = os.path.split(node.local_path)
    current_app.logger.info('download: path:%s, filename=%s'%(_path, _filename))
    response = make_response(send_from_directory(_path, filename=_filename, as_attachment=True))
    response.headers["Content-Disposition"] = "attachment; filename={}".format(_filename.encode().decode('latin-1'))
    return response

# get by ajax method
@users_bp.route('/tree', methods=['GET'])
@user_required('json')
def tree():
    path = request.args.get('path', '/')
    node = Node(path)
    return jsonify(node.tree)

# get by ajax method
@users_bp.route('/search', methods=['GET'])
@user_required('html')
def search():
    node_list = list()
    keywords = request.args.get('keywords', None)
    if keywords is None:
        return render_template('users/_search.html', keywords='', node_list=node_list)
    _keywords = list(filter(lambda s:len(s)>0, keywords.split()))
    for root, dirs, files in os.walk(current_user.home):
        for fname in files:
            for keyword in _keywords:
                if fname.find(keyword) != -1:
                    _suffix = root[len(current_user.home):].replace(os.path.sep, "/")
                    _dir = '/' if _suffix == '' else _suffix
                    _path = _dir + fname if _dir == '/' else _dir + '/' + fname
                    d = dict(name=fname, dir=_dir, path=_path)
                    node_list.append(d)
    return render_template('users/_search.html', keywords=keywords, node_list=node_list)

pubdisk/templates/_modal.html
<div id="modal-showmsg" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title">Message.</h4>
            </div>
            <div id="showmsg" class="modal-body">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{% if current_user.is_authenticated %}
<div id="modal-changepasswd" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title">Change password</h4>
            </div>
            <div class="modal-body">
                <form id="changepasswd">
                    <input name="csrf_token" type="hidden" value="{{csrf_token()}}">
                    <div class="form-group">
                        <label for="old_password">Old password</label>
                        <input id="old_password" name="old_password" type="password" class="form-control" placeholder="Input old password.">
                    </div>
                    <div class="form-group">
                        <label for="new_password">New password</label>
                        <input id="new_password" name="new_password" type="password" class="form-control" placeholder="Input new password,Length between 5 and 20.">
                    </div>
                    <div class="form-group">
                        <label for="confirm_new_password">Confirm new password</label>
                        <input id="confirm_new_password" name="confirm_new_password" type="password" class="form-control" placeholder="Input new password again.">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endif %}

pubdisk/templates/_nav.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {% if current_user.is_authenticated %}
            <a class="navbar-brand" href="{{url_for('users.index')}}">{{brand_name}}</a>
            {% else %}
            {% if current_user.role_admin %}
            <a class="navbar-brand" href="{{url_for('admin.index')}}">{{brand_name}}</a>
            {% else %}
            <a class="navbar-brand" href="{{url_for('users.main')}}">{{brand_name}}</a>
            {% endif %}
            {% endif %}
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            {% if current_user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span><span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">Account settings</li>
                        <li><a href="#modal-changepasswd" data-toggle="modal">Change password</a></li>
                  </ul>
                </li>
            </ul>
            {% if not current_user.role_admin %}
            <ul class="nav navbar-form navbar-right">
                <li><input id="search-keywords" type="text" placeholder="Search files..." class="form-control"></li>
            </ul>
            {% endif %}
            {% endif %}
        </div><!--/.navbar-collapse -->
    </div>
</nav>

pubdisk/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="csrf-token" content="{{csrf_token()}}">
	<title>{%block title%}{{brand_name}}{%endblock%}</title>
	<link href="{{url_for('static', filename='bootstrap/3.3.7/css/bootstrap.min.css')}}" rel="stylesheet">
	<link href="{{url_for('static', filename='jstree/3.3.9/themes/default/style.min.css')}}" rel="stylesheet">
	<link href="{{url_for('static', filename='pubdisk/1.0.0/css/pubdisk.css')}}" rel="stylesheet">
	
	<!--[if lt IE 9]>
	  <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
	  <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
	<![endif]-->
</head> 
<body>
{% include '_nav.html' %}
{% include '_modal.html' %}
<div class="adms-main">
{% block main %}
{% endblock %}
</div>

<script src="{{url_for('static', filename='jquery/1.12.4/jquery.min.js')}}"></script>
<script src="{{url_for('static', filename='bootstrap/3.3.7/js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static', filename='jquery.validate/1.17.0/jquery.validate.min.js')}}"></script>
<script src="{{url_for('static', filename='jstree/3.3.9/jstree.min.js')}}"></script>
<script src="{{url_for('static', filename='pubdisk/1.0.0/js/pubdisk.js')}}"></script>
<script>
$(document).ready(function(){
	$("#modal-changepasswd").on('show.bs.modal', function(e){
		var $this = $(this);
		var $modal_dialog = $this.find('.modal-dialog');
		$this.css('display', 'block');
		$modal_dialog.css({'margin-top': Math.max(0, ($(window).height() - $modal_dialog.height()) / 2) });
	});

	$("#changepasswd").submit(function(e){
		if (!$("#changepasswd").valid()){
			e.preventDefault();
			return;
		}
		$.post("{{url_for('auth.change_password')}}",
			$("#changepasswd").serialize(), 
			function(data){
				if (data.code == 0) {
					alert("Password change success, Will be redirect to sign in.");
					window.location.href = "{{url_for('auth.login')}}";
				} else {
					alert("Password change failed:" + data.msg);
				}
			}, "json"
		);

		$("#modal-changepasswd").modal('hide');
		e.preventDefault();
		$(this)[0].reset();
	});

	// change password form validate.
	$("#changepasswd").validate({
		rules: {
			old_password: "required",
			new_password: {
				required: true,
				minlength: 5,
				maxlength: 20
			},
			confirm_new_password: {
				equalTo: "#new_password"
			}
		},
		messages: {
			old_password: "Input old password.",
			new_password: {
				required: "Input new password.",
				minlength: "Length less than 5 characters.",
				maxlength: "Length more than 20 characters."
			},
			new_password_confirm: {
				equalTo: "Please enter the same value again."
			}
		}
	});

	// search files in website.
	$("#search-keywords").keyup(function(e){
		if (e.keyCode == 13) {
			// Enter key press down.
			keywords = $.trim($(this).val());
			if (keywords !== "") {
				console.log("keywords:" + keywords);
				window.location.hash = "#/search?keywords=" + keywords;
				$(this).val("");
			}
		}
	});
});
</script>
{% block script %}
{% endblock %}
</body>
</html>