pubdisk/blueprints/users.py
# -*- coding: utf-8 -*-
"""
:author: Zhazh
:copyright: © 2020 Zhazh <zhazh1985@163.com>
:license: MIT, see LICENSE for more details.
"""

import os
from flask import (
        render_template, redirect, url_for, request, jsonify, abort,
        Blueprint, current_app, send_from_directory, make_response
)
from flask_login import login_user, logout_user, login_required, current_user

from pubdisk.extensions import db
from pubdisk.blueprints import login_redirect, user_required
from pubdisk.utils import Node, NodeTypes

users_bp = Blueprint('users', __name__)

@users_bp.route('/')
@login_redirect
def index():
    return redirect(url_for('auth.login'))

#: main page will load other page by ajax get method.
@users_bp.route('/main')
@login_required
def main():
    return render_template('users/main.html')

# get by ajax method
@users_bp.route('/home', methods=["GET"])
@user_required('html')
def home():
    path = request.args.get('path', '/')
    node = Node(path)
    return render_template('users/_home.html', paths=node.layer_path, node_list=node.children)

@users_bp.route('/download', methods=["GET"])
@user_required('html')
def download():
    path = request.args.get('path', '/')
    node = Node(path)
    if not os.path.exists(node.local_path) or not os.path.isfile(node.local_path):
        abort(400)
    _path, _filename = os.path.split(node.local_path)
    current_app.logger.info('download: path:%s, filename=%s'%(_path, _filename))
    response = make_response(send_from_directory(_path, filename=_filename, as_attachment=True))
    response.headers["Content-Disposition"] = "attachment; filename={}".format(_filename.encode().decode('latin-1'))
    return response

# get by ajax method
@users_bp.route('/tree', methods=['GET'])
@user_required('json')
def tree():
    path = request.args.get('path', '/')
    node = Node(path)
    return jsonify(node.tree)

# get by ajax method
@users_bp.route('/search', methods=['GET'])
@user_required('html')
def search():
    node_list = list()
    keywords = request.args.get('keywords', None)
    if keywords is None:
        return render_template('users/_search.html', keywords='', node_list=node_list)
    _keywords = list(filter(lambda s:len(s)>0, keywords.split()))
    for root, dirs, files in os.walk(current_user.home):
        for fname in files:
            for keyword in _keywords:
                if fname.find(keyword) != -1:
                    _suffix = root[len(current_user.home):].replace(os.path.sep, "/")
                    _dir = '/' if _suffix == '' else _suffix
                    _path = _dir + fname if _dir == '/' else _dir + '/' + fname
                    d = dict(name=fname, dir=_dir, path=_path)
                    node_list.append(d)
    return render_template('users/_search.html', keywords=keywords, node_list=node_list)

pubdisk/templates/users/_home.html
<div class="path">
    <ol class="breadcrumb">
        {% for path in paths %}
        <li><a href="#{{url_for('users.home', path=path['path'])}}">{{path['name']}}</a></li>
        {% endfor %}
    </ol>
</div>

<div class="node-list">
    <table class="table">
        <tr>
            <td>Created</td>
            <td>Name</td>
            <td>Type</td>
            <td>Size</td>
            <td>Last Visit</td>
            <td>Last modify</td>
        </tr>
        {% for node in node_list %}
        <tr>
            <td>{{node['create']}}</td>
            {% if node['is_dir'] %}
            <td><a href="#{{url_for('users.home', path=node['path'])}}">{{node['name']}}</a></td>
            {% else %}
            {% if node['type'] == NodeTypes.AudioFile %}
            <td><a name="player" href="#audio-player" data-toggle="modal" src="{{url_for('users.download', path=node['path'])}}">{{node['name']}}</a></td>
            {% elif node['type'] == NodeTypes.VideoFile %}
            <td><a name="player" href="#video-player" data-toggle="modal" src="{{url_for('users.download', path=node['path'])}}">{{node['name']}}</a></td>
            {% else %}
            <td><a href="{{url_for('users.download', path=node['path'])}}">{{node['name']}}</a></td>
            {% endif %}
            {% endif %}
            <td>{{node['type'].name}}</td>
            <td>{{node['size']}}</td>
            <td>{{node['visit']}}</td>
            <td>{{node['modify']}}</td>
        </tr>
        {% endfor %}
    </table>    
</div>

<div id="audio-player" name="player" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <audio name="player" src="" controls="controls" autoplay></audio>
                <a name="download" href="" class="btn btn-info">Downloads</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="video-player" name="player" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <video name="player" src="" controls="controls" width="565" autoplay></video>
                <a name="download" href="" class="btn btn-info">Downloads</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
$(document).ready(function(){
    /*
      Provide auido/video player for {mp3, wav}/{mp4, mov} file.
      ===========================================
    */
    $("a[name='player']").on("click", function(e){
        var url = $(this).attr("src");
        var modal_id = $(this).attr("href");
        // set audio/video play src.
        $(modal_id).find("[name='player']").attr("src", url);
        // set audio/video download href.   
        $(modal_id).find("[name='download']").attr("href", url);
    });

    $("div.modal[name='player']").on("hide.bs.modal", function(e){
        $(this).find("[name='player']")[0].pause();
    });

    // Set modal box position when appeared.
	$("div.modal[name='player']").on('show.bs.modal', function(e){
		var $this = $(this);
		var $modal_dialog = $this.find('.modal-dialog');
		$this.css('display', 'block');
		$modal_dialog.css({'margin-top': Math.max(0, ($(window).height() - $modal_dialog.height()) / 2) });
	});
});
</script>

pubdisk/templates/users/_search.html
<div class="path">
Result of search "{{keywords}}" files.
</div>
<div class="node-list">
    <table class="table">
        <tr>
            <td>Directory</td>
            <td>Name</td>
        </tr>
        {% for node in node_list %}
        <tr>
            <td><a href="#{{url_for('users.home', path=node['dir'])}}">{{node["dir"]}}</a></td>
            <td><a href="{{url_for('users.download', path=node['path'])}}">{{node["name"]}}</a></td>
        </tr>
        {% endfor %}
    </table>    
</div>

pubdisk/templates/users/main.html
{% extends 'base.html' %}

{% block main %}
<div class="adms-sidebar">
    <div id="menu-tree">
    </div>
</div>
<div class="adms-page">
</div>
{% endblock %}

{% block script %}
<script>
$(document).ready(function(){
    $(window).bind("hashchange", function(){
        var hash = window.location.hash.replace('#', '');
        var url = hash;
        $.get(url, function(data){
            $(".adms-page").hide().html(data).show();
        });
    });

    if (window.location.hash === "") {
        window.location.hash = "#/home";
    } else {
        $(window).trigger("hashchange");
    }

    $('#menu-tree').jstree({ 'core' : {
            'data' : {'asyn':true, 'url':"{{url_for('users.tree')}}"}
        }
    });

    $('#menu-tree').on("changed.jstree", function (e, data) {
        console.log(data.selected[0]);
        url = data.selected[0]
        if (url === "/") {
            window.location.hash = "#/home";
        } else {
            window.location.hash = "#/home?path=" + url;
        }
    });
});
</script>
{% endblock %}